# Generated by Django 4.2.7 on 2023-12-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_full_name_userdetails_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(default='Doe', max_length=10),
            preserve_default=False,
        ),
    ]
