# Generated by Django 4.2.7 on 2023-12-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdetails_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
