# Generated by Django 5.0.1 on 2024-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='pincode',
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default='xs', max_length=10),
            preserve_default=False,
        ),
    ]
