# Generated by Django 5.0.1 on 2024-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order_statuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statuss',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatch'), (3, 'On the way'), (4, 'Delivered'), (5, 'Cancelled'), (6, 'Return')], default=1),
        ),
    ]
