# Generated by Django 5.0.1 on 2024-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_products_image1_products_image2_products_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
